CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Time parameters
SECONDS_PER_SLOT: 60
SLOTS_PER_EPOCH: 128

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: Z4242424242424242424242424242424242424242
